version: '2'
services:
  web:
    build: .
    depends_on:
    - db
    ports:
    - "5000:5000"
    volumes:
      - "./static:/app/statics"
#      - type: bind
#        source: ./static
#        target: /app/statics

  db:
    image: postgres
    ports:
    - "5432:5432"
    volumes:
      - "dbvolume:/var/lib/postgresql/data"
#     - "./dbdata:/var/lib/postgresql/data"
#      - type: bind
#        source: ./dbdata
#        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: "flaskapp"
      POSTGRES_PASSWORD: "hunter2"

volumes:
  dbvolume:
    external: true
